/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_javaherobrine_GameUtils */

#ifndef _Included_io_github_javaherobrine_GameUtils
#define _Included_io_github_javaherobrine_GameUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_javaherobrine_GameUtils
 * Method:    address
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_io_github_javaherobrine_GameUtils_address
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
