/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_javaherobrine_experimental_LinkedListSplicer */

#ifndef _Included_io_github_javaherobrine_experimental_LinkedListSplicer
#define _Included_io_github_javaherobrine_experimental_LinkedListSplicer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_javaherobrine_experimental_LinkedListSplicer
 * Method:    splice
 * Signature: (Ljava/util/LinkedList;Ljava/util/LinkedList;Ljava/lang/Class;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_io_github_javaherobrine_experimental_LinkedListSplicer_splice
  (JNIEnv *, jclass, jobject, jobject, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
